from .inline import (get_register_inline_keyboard,
                     understand_secret_phrase_inline_keyboard,
                     about_secret_phrase_inline_keyboard,
                     user_menu_inline_keyboard,
                     back_to_menu_inline_keyboard,
                     product_menu_inline_keyboard,
                     get_basket_menu,
                     checkout_menu_inline_keyboard,
                     checkout_cancellation_inline_keyboard,
                     get_choice_delivery,
                     checkout_address_menu_inline_keyboard,
                     delete_message_inline_keyboard,
                     discussion_menu_inline_keyboard,
                     discussion_cancel_inline_keyboard,
                     review_menu_inline_keyboard)
